version: '3'

services:
  api:
    image: node:10.16.0-alpine
    volumes: 
      - ./server:/usr/app
    working_dir: /usr/app
    ports:
      - 5000:5000
    command: npm run dev
    depends_on: 
      - mongo
  client:
    image: node:10.16.0-alpine
    volumes: 
      - ./client:/usr/client
    working_dir: /usr/client
    ports:
      - 3000:3000
    command: npm start

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
